pipeline {
  agent {
    label 'docker'
  }
  parameters {
    string(name: 'BUILD_BRANCH', defaultValue: 'master', description: 'Branch to build')
    string(name: 'VERSION', defaultValue: '1.0.0', description: 'version to name the rpm')
  }
  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr:'20'))
    timeout(time: 50, unit: 'MINUTES')
  }
  stages {
    stage('Notify') {
      steps {
        sh """
          curl -X POST -H "Content-Type: application/json" -d '{"attachments": [{"color": "#FFFF00", "text":":rocket: STARTED: Job '"$JOB_NAME"' ['"$BUILD_NUMBER"'] ('"$BUILD_URL"')"}]}' "https://tetration.slack.com/services/hooks/jenkins-ci?token=l9Wym3dTxAzelbNZcmWZQTTy"
        """
      }
    }
    stage('Checkout') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: "*/${params.BUILD_BRANCH}"]],
          doGenerateSubmoduleConfigurations: false,
          extensions: [
            [$class: 'CleanBeforeCheckout']
           ],
          submoduleCfg: [],
          userRemoteConfigs: [[
            url: 'git@github.com:TetrationAnalytics/url-to-pdf-api.git',
            refspec: '+refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/remotes/origin/tags/*'
          ]]
        ])
      }
    }
    stage('Build') {
      steps {
        sh """
          cd builder-setup && make BUILD_BRANCH=${params.BUILD_BRANCH} VERSION=${params.VERSION} -f Makefile.docker build && ls -a rpms/
        """
      }
    }
    stage('Deliver') {
      steps {
        sh """
          cd builder-setup && make deliver VERSION=${params.VERSION}
        """
      }
    }
  }
  post {
    success {
      sh """
        curl -X POST -H "Content-Type: application/json" -d '{"attachments": [{"color": "#00FF00", "text":":sunny: SUCCESSFUL: Job '"$JOB_NAME"' ['"$BUILD_NUMBER"'] ('"$BUILD_URL"')"}]}' "https://tetration.slack.com/services/hooks/jenkins-ci?token=l9Wym3dTxAzelbNZcmWZQTTy"
      """
    }
    failure {
      sh """
        curl -X POST -H "Content-Type: application/json" -d '{"attachments": [{"color": "#FF0000", "text":":bomb: FAILED: Job '"$JOB_NAME"' ['"$BUILD_NUMBER"'] ('"$BUILD_URL"')"}]}' "https://tetration.slack.com/services/hooks/jenkins-ci?token=l9Wym3dTxAzelbNZcmWZQTTy"
      """
    }
  }
}
